llm_api:
  GPT4V:
    model_name: "gpt-4o-vision-preview"
    openai_api_key: "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"
    target_url: "https://api.openai.com/v1/chat/completions"
  temperature: 1.0
  top_p: 0.9
  max_tokens: 500

automaton:
  language: "en"
  operation_system: "linux"
  prompt_tepmlate_dir: "prompt"
  auto_transitions: true
  auto_execute_actions: true

remote_vnc_server:
  host: "localhost"
  port: 5901
  password: "changeme"
  use_remote_clipboard: false
  remote_clipboard_host: "localhost"
  remote_clipboard_port: 8001
  remote_clipboard_secret_token: "changeme"
  task_list: "tasks.txt"
